import streamlit as st
import logging
import pandas as pd
from modules.text_processor import extract_all, chunk_text
from modules.quiz_generator import generate_quiz, generate_fusion_quiz, generate_explanation, generate_redemption_questions
from modules.evaluator import evaluate_short_answer
from utils.parser import parse_json

# Setup root logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(name)s: %(message)s'
)
logger = logging.getLogger(__name__)

# --- UI Setup ---
st.set_page_config(page_title="Active Learning AI", page_icon="🧠", layout="wide")

st.markdown("""
<div style='text-align: center; margin-bottom: 2rem;'>
    <h1 style='color: #2e6c80;'>🧠 Active Learning AI</h1>
    <p style='font-size: 1.2rem; color: #555;'>Adaptive personalized learning built on Bloom's Taxonomy</p>
</div>
""", unsafe_allow_html=True)

tab1, tab2 = st.tabs(["📄 Single Text", "📚 Multi-Doc Fusion"])

# Session State Initialization
if "quiz" not in st.session_state:
    st.session_state.quiz = None
if "level" not in st.session_state:
    st.session_state.level = "easy"
if "score" not in st.session_state:
    st.session_state.score = 0
if "round_submitted" not in st.session_state:
    st.session_state.round_submitted = False
if "round_results" not in st.session_state:
    st.session_state.round_results = {}

# Advanced Hybrid Logic States
if "concept_scores" not in st.session_state:
    st.session_state.concept_scores = {}
if "missed_concepts" not in st.session_state:
    st.session_state.missed_concepts = set()
if "redemption_mode" not in st.session_state:
    st.session_state.redemption_mode = False
if "redemption_questions" not in st.session_state:
    st.session_state.redemption_questions = []
if "redemption_submitted" not in st.session_state:
    st.session_state.redemption_submitted = False
if "redemption_results" not in st.session_state:
    st.session_state.redemption_results = []

def reset_quiz_state(quiz):
    logger.info("Resetting quiz state...")
    st.session_state.quiz = quiz
    st.session_state.level = "easy"
    st.session_state.score = 0
    st.session_state.round_submitted = False
    st.session_state.round_results = {}
    st.session_state.concept_scores = {}
    st.session_state.missed_concepts = set()
    st.session_state.redemption_mode = False
    st.session_state.redemption_questions = []
    st.session_state.redemption_submitted = False
    st.session_state.redemption_results = []

# --- Sidebar Configuration ---
with st.sidebar:
    st.header("⚙️ Configuration")
    user_api_key = st.text_input("Enter your Groq API Key:", type="password", help="Get your free API key at console.groq.com")
    if not user_api_key:
        st.warning("Please enter your Groq API Key to proceed.")
    st.markdown("---")

# --- Tab 1: Single Text ---
with tab1:
    text = st.text_area("Enter subject matter or study content:", height=200)
    if st.button("Generate Adaptive Quiz", use_container_width=True):
        if not user_api_key:
            st.error("Please enter your Groq API key in the sidebar first.")
        elif text.strip():
            with st.spinner("Analyzing text and calibrating cognitive difficulties..."):
                raw = generate_quiz(text, api_key=user_api_key)
                if raw is None:
                    st.error("Failed to connect to AI service.")
                else:
                    quiz = parse_json(raw)
                    if quiz:
                        reset_quiz_state(quiz)
                        st.success("Quiz successfully generated! Scroll down to start.")
                    else:
                        st.error("Failed to parse quiz generated by AI.")
        else:
            st.warning("Please enter some text.")

# --- Tab 2: Fusion Quiz ---
with tab2:
    uploaded_files = st.file_uploader("Upload Topic PDFs", accept_multiple_files=True, type=["pdf"])
    if st.button("Generate Fusion Adaptive Quiz", use_container_width=True):
        if not user_api_key:
            st.error("Please enter your Groq API key in the sidebar first.")
        elif uploaded_files:
            with st.spinner("Extracting content and fusing core concepts..."):
                all_text = extract_all(uploaded_files)
                if all_text.strip():
                    chunks = list(chunk_text(all_text, 400))
                    raw = generate_fusion_quiz(chunks, api_key=user_api_key)
                    if raw is None:
                        st.error("Failed to connect to AI service.")
                    else:
                        quiz = parse_json(raw)
                        if quiz:
                            reset_quiz_state(quiz)
                            st.success("Fusion quiz generated! Scroll down to start.")
                        else:
                            st.error("Failed to parse fusion quiz generated by AI.")
                else:
                    st.error("No text could be extracted from PDFs.")
        else:
            st.warning("Please upload at least one PDF.")

# --- Adaptive Quiz Interface ---
if st.session_state.quiz:
    st.markdown("---")
    
    # Analytics Dashboard (Sidebar)
    with st.sidebar:
        st.header("📊 Analytics Dashboard")
        total_questions = sum([stats["total"] for stats in st.session_state.concept_scores.values()])
        correct_questions = sum([stats["correct"] for stats in st.session_state.concept_scores.values()])
        accuracy = (correct_questions / total_questions * 100) if total_questions > 0 else 0
        st.metric("Overall Accuracy", f"{accuracy:.1f}%")
        
        if st.session_state.concept_scores:
            df = pd.DataFrame([
                {"Concept": concept, "Score (%)": (stats["correct"] / stats["total"]) * 100}
                for concept, stats in st.session_state.concept_scores.items()
            ])
            st.bar_chart(df.set_index("Concept"))
            
        if st.session_state.missed_concepts:
            st.warning("Needs Review: " + ", ".join(st.session_state.missed_concepts))
    
    # Main Quiz Flow
    if not st.session_state.redemption_mode:
        quiz = st.session_state.quiz
        current_level = st.session_state.level
        
        if "concepts" in quiz and current_level == "easy" and not st.session_state.round_submitted:
            with st.container():
                st.info("💡 **Global Extracted Concepts:** " + ", ".join(quiz["concepts"]))
        
        col1, col2, col3 = st.columns(3)
        col1.metric("Cognitive Level", current_level.capitalize())
        col2.metric("Cumulative Score", st.session_state.score)
        col3.metric("Status", "Reviewing" if st.session_state.round_submitted else "In Progress")
        
        st.markdown("---")
        
        questions = quiz.get(current_level, [])
        
        if not questions:
            st.error(f"Failed to load questions for {current_level} level.")
        else:
            if not st.session_state.round_submitted:
                st.subheader(f"Level: {current_level.capitalize()}")
                with st.form("adaptive_quiz_form"):
                    for i, q in enumerate(questions):
                        concept_label = q.get('concept', 'General')
                        st.markdown(f"**Q{i+1} [{concept_label}]: {q['question']}**")
                        
                        if "hint" in q:
                            with st.expander("💡 Request Hint"):
                                st.write(q["hint"])
                                
                        st.radio("Options", q["options"], key=f"q_{current_level}_{i}", label_visibility="collapsed")
                        st.markdown("<br/>", unsafe_allow_html=True)
                        
                    submitted = st.form_submit_button("Submit Answers")
                    
                if submitted:
                    with st.spinner("Grading and generating AI feedback..."):
                        round_score = 0
                        feedback_details = []
                        for i, q in enumerate(questions):
                            user_choice = st.session_state.get(f"q_{current_level}_{i}")
                            is_correct = (user_choice == q["answer"])
                            concept = q.get("concept", "General")
                            
                            # Update Analytics
                            if concept not in st.session_state.concept_scores:
                                st.session_state.concept_scores[concept] = {"correct": 0, "total": 0}
                            st.session_state.concept_scores[concept]["total"] += 1
                            
                            if is_correct:
                                round_score += 1
                                st.session_state.concept_scores[concept]["correct"] += 1
                            else:
                                st.session_state.missed_concepts.add(concept)
                            
                            # Explainability Layer
                            explanation = ""
                            if not is_correct:
                                explanation = generate_explanation(q["question"], user_choice, q["answer"], concept, api_key=user_api_key)
                            
                            feedback_details.append({
                                "question": q["question"],
                                "user_choice": user_choice,
                                "correct_answer": q["answer"],
                                "is_correct": is_correct,
                                "explanation": explanation
                            })
                        
                        def get_next_level_linear(current):
                            if current == "easy": return "medium"
                            if current == "medium": return "hard"
                            return "hard"
                                
                        next_lvl = get_next_level_linear(current_level)
                        st.session_state.round_results = {
                            "score": round_score,
                            "max": len(questions),
                            "next": next_lvl,
                            "details": feedback_details
                        }
                        st.session_state.round_submitted = True
                        
                        if round_score == len(questions):
                            st.balloons()
                        st.rerun()
                        
            else:
                # Review Round Results
                res = st.session_state.round_results
                st.header("🎯 Round Results")
                st.write(f"You answered **{res['score']} out of {res['max']}** correctly.")
                
                for i, detail in enumerate(res["details"]):
                    if detail["is_correct"]:
                        st.success(f"**Q{i+1}: {detail['question']}**\n\nCorrect! ({detail['correct_answer']})")
                    else:
                        st.error(f"**Q{i+1}: {detail['question']}**\n\nYou chose: {detail['user_choice']}\n\nCorrect Answer: {detail['correct_answer']}\n\n**AI Teacher:**\n{detail['explanation']}")
                
                st.markdown("---")
                
                if current_level == "hard" and res["next"] == "hard":
                    if len(st.session_state.missed_concepts) > 0:
                        st.subheader("📚 Let's review some missed concepts!")
                        st.info("You completed the main quiz, but there are a few areas we should review.")
                        if st.button("Start Redemption Round", type="primary"):
                            with st.spinner("Generating targeted short-answer questions..."):
                                raw_redemption = generate_redemption_questions(list(st.session_state.missed_concepts), api_key=user_api_key)
                                parsed = parse_json(raw_redemption)
                                if parsed and "questions" in parsed:
                                    st.session_state.redemption_questions = parsed["questions"]
                                    st.session_state.redemption_mode = True
                                    st.rerun()
                                else:
                                    st.error("Failed to generate redemption round. Please complete the quiz.")
                                    if st.button("Finish Quiz"):
                                        st.session_state.quiz = None
                                        st.rerun()
                    else:
                        st.subheader("🎉 Perfect Mastery!")
                        st.info("🏆 **You completed the hardest difficulty with no missed concepts!**")
                        if st.button("Start New Topic", type="primary"):
                            st.session_state.quiz = None
                            st.rerun()
                else:
                    st.subheader(f"Adaptive Update: Next level -> {res['next'].capitalize()}")
                    if st.button("Continue to Next Round", type="primary"):
                        st.session_state.score += res["score"]
                        st.session_state.level = res["next"]
                        st.session_state.round_submitted = False
                        st.session_state.round_results = {}
                        st.rerun()

    # Redemption Mode (Semantic Evaluation)
    else:
        st.header("🔄 Redemption Round")
        st.write("Answer these short-answer questions to prove your understanding of the concepts you missed.")
        
        if not st.session_state.redemption_submitted:
            with st.form("redemption_form"):
                for i, q in enumerate(st.session_state.redemption_questions):
                    st.markdown(f"**Q{i+1} [{q.get('concept', 'Review')}]: {q['question']}**")
                    st.text_area("Your Answer", key=f"redemption_ans_{i}", height=100)
                    st.markdown("<br/>", unsafe_allow_html=True)
                
                redemption_submit = st.form_submit_button("Submit Semantic Evaluation")
                
            if redemption_submit:
                with st.spinner("Semantically evaluating your answers..."):
                    results = []
                    for i, q in enumerate(st.session_state.redemption_questions):
                        user_ans = st.session_state.get(f"redemption_ans_{i}", "")
                        eval_raw = evaluate_short_answer(q["question"], q["correct_answer"], user_ans, api_key=user_api_key)
                        eval_parsed = parse_json(eval_raw)
                        
                        if eval_parsed:
                            results.append({
                                "question": q["question"],
                                "user_ans": user_ans,
                                "reference": q["correct_answer"],
                                "score": eval_parsed.get("score", 0),
                                "is_correct": eval_parsed.get("correctness", False),
                                "reasoning": eval_parsed.get("reasoning", "No detailed reasoning provided.")
                            })
                        else:
                            results.append({
                                "question": q["question"],
                                "user_ans": user_ans,
                                "reference": q["correct_answer"],
                                "score": 0,
                                "is_correct": False,
                                "reasoning": "Failed to parse AI evaluation."
                            })
                    
                    st.session_state.redemption_results = results
                    st.session_state.redemption_submitted = True
                    st.rerun()
                    
        else:
            # Show Redemption Results
            st.subheader("Redemption Results")
            for i, res in enumerate(st.session_state.redemption_results):
                if res["is_correct"]:
                    st.success(f"**Q{i+1} (Score: {res['score']}/5)**\n\n**Your Answer:** {res['user_ans']}\n\n**AI Evaluation:** {res['reasoning']}")
                else:
                    st.error(f"**Q{i+1} (Score: {res['score']}/5)**\n\n**Your Answer:** {res['user_ans']}\n\n**AI Evaluation:** {res['reasoning']}\n\n*(Reference Idea: {res['reference']})*")
                    
            st.markdown("---")
            st.info("You've completed the learning loop!")
            if st.button("Start New Topic", type="primary"):
                st.session_state.quiz = None
                st.rerun()
